#nullable enable
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace Routya.ResultKit
{
    /// <summary>
    /// Represents a machine-readable format for specifying errors in HTTP API responses based on RFC 7807.
    /// </summary>
    [JsonConverter(typeof(Serialization.ProblemDetailsJsonConverter))]
    public class ProblemDetails
    {
        private readonly Dictionary<string, object?> _extensions = new Dictionary<string, object?>();

        /// <summary>
        /// A URI reference that identifies the problem type. Defaults to "about:blank".
        /// </summary>
        public string Type { get; init; } = "about:blank";

        /// <summary>
        /// A short, human-readable summary of the problem type.
        /// </summary>
        public string? Title { get; init; }

        /// <summary>
        /// The HTTP status code generated by the origin server for this occurrence of the problem.
        /// </summary>
        public int? Status { get; init; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        public string? Detail { get; init; }

        /// <summary>
        /// A URI reference that identifies the specific occurrence of the problem.
        /// </summary>
        public string? Instance { get; init; }

        /// <summary>
        /// Sets an extension member to be serialized as a top-level property in the JSON output.
        /// </summary>
        /// <typeparam name="T">The type of the extension value.</typeparam>
        /// <param name="key">The key for the extension member.</param>
        /// <param name="value">The value to store.</param>
        public void SetExtension<T>(string key, T value)
        {
            if (string.IsNullOrWhiteSpace(key))
                throw new ArgumentException("Extension key cannot be null or whitespace.", nameof(key));

            _extensions[key] = value;
        }

        /// <summary>
        /// Tries to get an extension member value.
        /// </summary>
        /// <typeparam name="T">The expected type of the extension value.</typeparam>
        /// <param name="key">The key for the extension member.</param>
        /// <param name="value">The retrieved value if found and convertible.</param>
        /// <returns>True if the extension exists and could be converted to the specified type; otherwise false.</returns>
        public bool TryGetExtension<T>(string key, [NotNullWhen(true)] out T? value)
        {
            if (_extensions.TryGetValue(key, out var objValue) && objValue is T typedValue)
            {
                value = typedValue;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets all extension members for serialization purposes.
        /// </summary>
        internal IReadOnlyDictionary<string, object?> GetExtensions() => _extensions;
    }
}
