<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
	  <LangVersion>8.0</LangVersion>
	  <SignAssembly>False</SignAssembly>
	  <Title>Routya.ResultKit</Title>
	  <Authors>Henry Bartosch</Authors>
	  <PackageId>Routya.ResultKit</PackageId>
	  <RepositoryUrl>https://github.com/HBartosch/Routya.ResultKit</RepositoryUrl>
	  <PackageProjectUrl>https://github.com/HBartosch/Routya.ResultKit</PackageProjectUrl>
	  <PackageTags>result, validation, data-annotations, problem-details, error-handling </PackageTags>
	  <Description>Lightweight result wrapper and validation toolkit for C# APIs. Includes Result, ProblemDetails, and powerful custom validation attributes.</Description>
	  <PackageIcon>PackageIconResized.png</PackageIcon>
	  <PackageLicenseFile>LICENSE</PackageLicenseFile>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
	
  <PropertyGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
  	<Nullable>enable</Nullable>
  </PropertyGroup>	

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
  	<None Include="..\LICENSE" Pack="true" PackagePath="" />
  	<None Include="..\README.md" Pack="true" PackagePath="" />
	<None Include="PackageIconResized.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
