using Microsoft.AspNetCore.Mvc;
using Routya.ResultKit;
using Routya.ResultKit.AspNetCore.Extensions;

namespace Routya.ResultKit.Demo.Api.Controllers;

/// <summary>
/// Demonstrates all ProblemDetails types and extension features
/// </summary>
[ApiController]
[Route("api/[controller]")]
public class ProblemDetailsController : ControllerBase
{
    /// <summary>
    /// 400 Bad Request - Invalid request format
    /// </summary>
    /// <remarks>
    /// Returns a BadRequest ProblemDetails with extensions showing what was invalid.
    /// </remarks>
    [HttpGet("bad-request")]
    [ProducesResponseType(typeof(Microsoft.AspNetCore.Mvc.ProblemDetails), StatusCodes.Status400BadRequest)]
    public IActionResult BadRequestExample()
    {
        var problem = Routya.ResultKit.Builders.ProblemDetailsBuilder.BadRequest("The request format is invalid")
            .WithExtension("expectedFormat", "JSON")
            .WithExtension("receivedFormat", "XML")
            .WithExtension("helpUrl", "https://api.example.com/docs/request-format")
            .Build();
        return Result<object>.Fail(problem).ToActionResult(HttpContext);
    }

    /// <summary>
    /// 401 Unauthorized - Authentication required
    /// </summary>
    /// <remarks>
    /// Returns an Unauthorized ProblemDetails with authentication scheme information.
    /// </remarks>
    [HttpGet("unauthorized")]
    [ProducesResponseType(typeof(Microsoft.AspNetCore.Mvc.ProblemDetails), StatusCodes.Status401Unauthorized)]
    public IActionResult UnauthorizedExample()
    {
        var problem = Routya.ResultKit.Builders.ProblemDetailsBuilder.Unauthorized("Authentication is required to access this resource")
            .WithExtension("authenticationScheme", "Bearer")
            .WithExtension("realm", "api.example.com")
            .Build();
        return Result<object>.Fail(problem).ToActionResult(HttpContext);
    }

    /// <summary>
    /// 403 Forbidden - Insufficient permissions
    /// </summary>
    /// <remarks>
    /// Returns a Forbidden ProblemDetails with required permissions information.
    /// </remarks>
    [HttpGet("forbidden")]
    [ProducesResponseType(typeof(Microsoft.AspNetCore.Mvc.ProblemDetails), StatusCodes.Status403Forbidden)]
    public IActionResult ForbiddenExample()
    {
        var problem = Routya.ResultKit.Builders.ProblemDetailsBuilder.Forbidden("You do not have permission to perform this action")
            .WithExtension("requiredPermission", "admin:write")
            .WithExtension("currentPermissions", new[] { "user:read", "user:write" })
            .WithExtension("contactSupport", "support@example.com")
            .Build();
        return Result<object>.Fail(problem).ToActionResult(HttpContext);
    }

    /// <summary>
    /// 404 Not Found - Resource doesn't exist
    /// </summary>
    /// <remarks>
    /// Returns a NotFound ProblemDetails with resource identification information.
    /// </remarks>
    [HttpGet("not-found/{resourceType}/{id}")]
    [ProducesResponseType(typeof(Microsoft.AspNetCore.Mvc.ProblemDetails), StatusCodes.Status404NotFound)]
    public IActionResult NotFoundExample(string resourceType, int id)
    {
        var problem = Routya.ResultKit.Builders.ProblemDetailsBuilder.NotFound($"{resourceType} with ID {id} was not found")
            .WithExtension("resourceType", resourceType)
            .WithExtension("resourceId", id)
            .WithExtension("searchedIn", "primary database")
            .WithExtension("suggestion", $"Verify the {resourceType} ID and try again")
            .Build();
        return Result<object>.Fail(problem).ToActionResult(HttpContext);
    }

    /// <summary>
    /// 409 Conflict - Resource state conflict
    /// </summary>
    /// <remarks>
    /// Returns a Conflict ProblemDetails with conflict details.
    /// </remarks>
    [HttpGet("conflict")]
    [ProducesResponseType(typeof(Microsoft.AspNetCore.Mvc.ProblemDetails), StatusCodes.Status409Conflict)]
    public IActionResult ConflictExample()
    {
        var problem = Routya.ResultKit.Builders.ProblemDetailsBuilder.Conflict("A user with this email already exists")
            .WithExtension("conflictingField", "email")
            .WithExtension("conflictingValue", "john@example.com")
            .WithExtension("existingResourceId", 123)
            .WithExtension("resolution", "Use a different email or update the existing user")
            .Build();
        return Result<object>.Fail(problem).ToActionResult(HttpContext);
    }

    /// <summary>
    /// 422 Unprocessable Entity - Validation errors
    /// </summary>
    /// <remarks>
    /// Returns an UnprocessableEntity ProblemDetails with detailed validation errors.
    /// This is automatically generated by the validation system, but can also be created manually.
    /// </remarks>
    [HttpGet("validation-error")]
    [ProducesResponseType(typeof(Microsoft.AspNetCore.Mvc.ProblemDetails), StatusCodes.Status422UnprocessableEntity)]
    public IActionResult ValidationErrorExample()
    {
        var errors = new Dictionary<string, List<string>>
        {
            ["name"] = new List<string> { "Name is required", "Name must be at least 2 characters" },
            ["email"] = new List<string> { "Email is required", "Invalid email format" },
            ["age"] = new List<string> { "Age must be between 18 and 120" }
        };

        var errorsArray = errors.ToDictionary(k => k.Key, v => v.Value.ToArray());
        var problem = Routya.ResultKit.Builders.ProblemDetailsBuilder.ValidationError(errorsArray)
            .WithDetail("One or more validation errors occurred")
            .WithExtension("validatedAt", DateTime.UtcNow)
            .WithExtension("validationSchema", "UserSchema v1.0")
            .Build();
        return Result<object>.Fail(problem).ToActionResult(HttpContext);
    }

    /// <summary>
    /// 500 Internal Server Error - Server error
    /// </summary>
    /// <remarks>
    /// Returns an InternalServerError ProblemDetails with error tracking information.
    /// Note: In production, you should avoid exposing internal error details.
    /// </remarks>
    [HttpGet("server-error")]
    [ProducesResponseType(typeof(Microsoft.AspNetCore.Mvc.ProblemDetails), StatusCodes.Status500InternalServerError)]
    public IActionResult ServerErrorExample()
    {
        var errorId = Guid.NewGuid().ToString();
        
        var problem = Routya.ResultKit.Builders.ProblemDetailsBuilder.InternalServerError("An unexpected error occurred while processing your request")
            .WithExtension("errorId", errorId)
            .WithExtension("timestamp", DateTime.UtcNow)
            .WithExtension("supportMessage", $"Please contact support with error ID: {errorId}")
            .Build();
        return Result<object>.Fail(problem).ToActionResult(HttpContext);
    }

    /// <summary>
    /// Custom status code - Any HTTP status code
    /// </summary>
    /// <remarks>
    /// You can create ProblemDetails for any HTTP status code.
    /// This example shows a 503 Service Unavailable.
    /// </remarks>
    [HttpGet("custom-status")]
    [ProducesResponseType(typeof(Microsoft.AspNetCore.Mvc.ProblemDetails), StatusCodes.Status503ServiceUnavailable)]
    public IActionResult CustomStatusExample()
    {
        var problemDetails = new Routya.ResultKit.ProblemDetails
        {
            Type = "https://api.example.com/problems/service-unavailable",
            Title = "Service Temporarily Unavailable",
            Status = 503,
            Detail = "The service is temporarily unavailable due to maintenance"
        };
        
        problemDetails.SetExtension("maintenanceWindow", "2024-11-19T10:00:00Z to 2024-11-19T12:00:00Z");
        problemDetails.SetExtension("estimatedRestoreTime", "2024-11-19T12:00:00Z");
        problemDetails.SetExtension("retryAfter", 3600);

        return Result<object>.Fail(problemDetails).ToActionResult(HttpContext);
    }

    /// <summary>
    /// Multiple extensions - Rich error context
    /// </summary>
    /// <remarks>
    /// Demonstrates adding multiple extensions to provide rich context about an error.
    /// Extensions can be of any JSON-serializable type.
    /// </remarks>
    [HttpGet("rich-error")]
    [ProducesResponseType(typeof(Microsoft.AspNetCore.Mvc.ProblemDetails), StatusCodes.Status400BadRequest)]
    public IActionResult RichErrorExample()
    {
        var problem = Routya.ResultKit.Builders.ProblemDetailsBuilder.BadRequest("Payment processing failed")
            .WithExtension("transactionId", "txn_123456789")
            .WithExtension("paymentMethod", "credit_card")
            .WithExtension("amount", new { value = 99.99, currency = "USD" })
            .WithExtension("failureReason", "insufficient_funds")
            .WithExtension("availableBalance", 45.50)
            .WithExtension("requiredAmount", 99.99)
            .WithExtension("retryable", true)
            .WithExtension("retryLimit", 3)
            .WithExtension("currentRetryCount", 1)
            .WithExtension("timestamp", DateTime.UtcNow)
            .WithExtension("metadata", new Dictionary<string, object>
            {
                ["customerSegment"] = "premium",
                ["loyaltyPoints"] = 1250,
                ["previousTransactions"] = 47
            })
            .Build();
        return Result<object>.Fail(problem).ToActionResult(HttpContext);
    }

    /// <summary>
    /// Success with data - 200 OK
    /// </summary>
    /// <remarks>
    /// Shows how to return successful results using the same Result pattern.
    /// </remarks>
    [HttpGet("success")]
    [ProducesResponseType(typeof(object), StatusCodes.Status200OK)]
    public IActionResult SuccessExample()
    {
        var data = new
        {
            message = "Operation completed successfully",
            processedAt = DateTime.UtcNow,
            items = new[] { "item1", "item2", "item3" }
        };

        return Result<object>.Ok(data).ToActionResult(HttpContext);
    }

    /// <summary>
    /// Success with custom status code - 201 Created
    /// </summary>
    [HttpGet("created")]
    [ProducesResponseType(typeof(object), StatusCodes.Status201Created)]
    public IActionResult CreatedExample()
    {
        var resource = new
        {
            id = 123,
            name = "New Resource",
            createdAt = DateTime.UtcNow
        };

        return Result<object>.Created(resource).ToActionResult(HttpContext);
    }
}
